version: 0.2

phases:
  pre_build:
    commands:
      - df -h
      - docker version
      - docker image ls
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_LOGIN_ENDPOINT
      - docker pull $CONTAINER_REPOSITORY_URL:$TAG_NAME || true

  build:
    commands:
      - cd ./al2/x86_64/standard/5.0
      - env
      - docker build --tag ${CONTAINER_REPOSITORY_URL}:${TAG_NAME} --cache-to mode=max,image-manifest=true,oci-mediatypes=true,type=registry,ref=${CONTAINER_REPOSITORY_URL}:cache --cache-from type=registry,ref=ref=${CONTAINER_REPOSITORY_URL}:cache .

  post_build:
    commands:
      - docker push $CONTAINER_REPOSITORY_URL
